# scout_v2_control.yaml  (ROS 2 / gz_ros2_control)
controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100

    # declare controllers aqui (nome → tipo)
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Parâmetros de cada controlador
joint_state_broadcaster:
  ros__parameters: {}

wheel_controller:
  ros__parameters:
    joints:
      - front_right_wheel
      - front_left_wheel
      - rear_left_wheel
      - rear_right_wheel
    state_interfaces: [position, velocity]
